import type { DashboardStats, SalesEntry } from "../backend.d";

// Base timestamp reference in nanoseconds
const BASE_NS = BigInt("1772150400000000000");
const DAY_NS = BigInt(86_400_000_000_000);

function parseTCV(raw: string): number {
  if (!raw || raw.trim() === "" || raw.trim() === "-") return 0;
  const s = raw.replace(/\$/g, "").replace(/,/g, "").trim();
  const mnMatch = s.match(/^([\d.]+)\s*[Mm][Nn]?$/);
  if (mnMatch) return Math.round(Number.parseFloat(mnMatch[1]) * 1_000_000);
  const kMatch = s.match(/^([\d.]+)\s*[Kk]$/);
  if (kMatch) return Math.round(Number.parseFloat(kMatch[1]) * 1_000);
  const num = Number.parseFloat(s.replace(/[^0-9.]/g, ""));
  return Number.isNaN(num) ? 0 : num;
}

// Raw data from the updated spreadsheet image
const rawEntries = [
  {
    received: "2025-01-30",
    source: "Account Mining",
    account: "LexisNexis Risk",
    potential: "States analysis & cases data keying",
    notes: "Proposal submitted",
    statusGroup: "In Progress",
    status: "Proposal Sent",
    salesPerson: "Kibran",
    zcrm: "79117800001552460000",
    tcvRaw: "$26,00,000",
    closing: "2026-03-31",
  },
  {
    received: "2025-03-05",
    source: "Account Mining",
    account: "DataAxle",
    potential: "International Business Data",
    notes: "Counts of companies shared with Kibran",
    statusGroup: "Closed",
    status: "Awaiting Customer Response",
    salesPerson: "Kibran",
    zcrm: "79117800001592900000",
    tcvRaw: "$20,000",
    closing: "2026-03-31",
  },
  {
    received: "2025-03-05",
    source: "Account Mining",
    account: "Fitch Group",
    potential: "Private Statements",
    notes: "Proposal shared with the customer",
    statusGroup: "In Progress",
    status: "Proposal Sent",
    salesPerson: "Cathy",
    zcrm: "79117800001626710320",
    tcvRaw: "$2,50,000",
    closing: "2026-03-31",
  },
  {
    received: "2025-03-21",
    source: "Account Mining",
    account: "Accutrend",
    potential: "Canada Federal Registry Data",
    notes: "Order Won",
    statusGroup: "Closed",
    status: "Closed Won",
    salesPerson: "Kibran",
    zcrm: "9117800001689000000",
    tcvRaw: "$1,92,000",
    closing: "2025-10-31",
  },
  {
    received: "2025-05-13",
    source: "Marketing Lead",
    account: "LakshX",
    potential: "Cab-fare data collection",
    notes: "",
    statusGroup: "Closed",
    status: "Closed – No Decision",
    salesPerson: "MJ",
    zcrm: "79117800001606930000",
    tcvRaw: "",
    closing: "2026-03-31",
  },
  {
    received: "2025-06-02",
    source: "Marketing Lead",
    account: "Vivantes",
    potential: "To update",
    notes: "Qualified",
    statusGroup: "New",
    status: "Assigned",
    salesPerson: "Cathy",
    zcrm: "79117800001623650130",
    tcvRaw: "",
    closing: "2026-03-31",
  },
  {
    received: "2025-06-25",
    source: "Account Mining",
    account: "Candid",
    potential: "Contact Information Extraction",
    notes: "Response to the feedback shared with the customer",
    statusGroup: "In Progress",
    status: "Awaiting Customer Feedback",
    salesPerson: "Kibran",
    zcrm: "79117800001643360000",
    tcvRaw: "$2,00,000",
    closing: "2026-03-31",
  },
  {
    received: "2025-07-23",
    source: "Account Mining",
    account: "Accutrend",
    potential: "SOS Data",
    notes: "Proposal submitted",
    statusGroup: "In Progress",
    status: "Proposal Sent",
    salesPerson: "Kibran",
    zcrm: "",
    tcvRaw: "",
    closing: "2026-03-31",
  },
  {
    received: "2025-09-05",
    source: "Sales Lead",
    account: "LexisNexis Risk",
    potential: "PDF files download",
    notes: "Proposal submitted",
    statusGroup: "In Progress",
    status: "Proposal Sent",
    salesPerson: "Kibran",
    zcrm: "79117800001552460200",
    tcvRaw: "$60,000",
    closing: "2026-03-31",
  },
  {
    received: "2025-09-09",
    source: "Marketing Lead",
    account: "True Step, LLC",
    potential: "To update",
    notes: "Qualified",
    statusGroup: "New",
    status: "Assigned",
    salesPerson: "Kibran",
    zcrm: "79117800001703720000",
    tcvRaw: "",
    closing: "2026-03-31",
  },
  {
    received: "2025-09-18",
    source: "Marketing Lead",
    account: "The Insights Shop",
    potential: "Lead Generation",
    notes: "Samples and Pricing shared",
    statusGroup: "New",
    status: "Assigned",
    salesPerson: "MJ",
    zcrm: "79117800001710780000",
    tcvRaw: "",
    closing: "2026-03-31",
  },
  {
    received: "2025-09-30",
    source: "Account Mining",
    account: "LexisNexis L&P",
    potential: "RFP - Company Data Automation",
    notes: "Proposal submitted. Demo rescheduled for Jan 21st.",
    statusGroup: "In Progress",
    status: "Demo Scheduled",
    salesPerson: "Kibran",
    zcrm: "79117800001721200000",
    tcvRaw: "$70,00,000",
    closing: "2026-03-31",
  },
  {
    received: "2025-10-03",
    source: "Account Mining",
    account: "Accutrend",
    potential: "Corporate TIN and/or EIN",
    notes:
      "Proposal submitted. Feedback received from Kibran. JK/Jayanth is exploring a few more approaches.",
    statusGroup: "In Progress",
    status: "Proposal Sent",
    salesPerson: "Kibran",
    zcrm: "79117800001723470000",
    tcvRaw: "$76,900",
    closing: "2026-03-31",
  },
  {
    received: "2025-10-06",
    source: "Sales Lead",
    account: "Cipla",
    potential: "Invoice Data Extraction",
    notes: "Revised SOW agreement shared with the customer.",
    statusGroup: "In Progress",
    status: "Awaiting Customer Feedback",
    salesPerson: "MJ",
    zcrm: "79117800001746480000",
    tcvRaw: "$14,000",
    closing: "2026-03-31",
  },
  {
    received: "2025-10-09",
    source: "Account Mining",
    account: "Accutrend",
    potential: "Fire Safety History",
    notes: "Response/Feedback received for the samples shared.",
    statusGroup: "In Progress",
    status: "Awaiting Customer Feedback",
    salesPerson: "Kibran",
    zcrm: "79117800001727470000",
    tcvRaw: "",
    closing: "2026-03-31",
  },
  {
    received: "2025-10-17",
    source: "Account Mining",
    account: "LexisNexis Risk",
    potential: "TX - Lubbock County",
    notes: "Proposal submitted",
    statusGroup: "In Progress",
    status: "Proposal Sent",
    salesPerson: "Kibran",
    zcrm: "",
    tcvRaw: "$864",
    closing: "2026-03-31",
  },
  {
    received: "2025-10-21",
    source: "Marketing Lead",
    account: "JSAN Consulting Group",
    potential: "To update",
    notes: "Qualified",
    statusGroup: "New",
    status: "Assigned",
    salesPerson: "MJ",
    zcrm: "79117800001737360020",
    tcvRaw: "",
    closing: "2026-03-31",
  },
  {
    received: "2025-10-22",
    source: "Account Mining",
    account: "Accutrend",
    potential: "B2B Tax Lien Data",
    notes: "Revised samples shared with the customer. (next year)",
    statusGroup: "Closed",
    status: "Awaiting Customer Response",
    salesPerson: "Kibran",
    zcrm: "79117800001738100000",
    tcvRaw: "",
    closing: "2026-03-31",
  },
  {
    received: "2025-10-29",
    source: "Marketing Lead",
    account: "ScoreMe",
    potential: "MCA and Unstructured Data Extraction",
    notes: "NDA Signed. Further requirements to be conversed.",
    statusGroup: "In Progress",
    status: "Awaiting Customer Feedback",
    salesPerson: "MJ",
    zcrm: "79117800001742520450",
    tcvRaw: "",
    closing: "2026-03-31",
  },
  {
    received: "2025-11-01",
    source: "Marketing Lead",
    account: "Alamo Tile & Stone",
    potential: "Image to Text",
    notes: "",
    statusGroup: "New",
    status: "Assigned",
    salesPerson: "Kibran",
    zcrm: "79117800001748450190",
    tcvRaw: "",
    closing: "2026-03-31",
  },
  {
    received: "2025-11-07",
    source: "Marketing Lead",
    account: "Zuber Group/Keller Williams Realty",
    potential: "Convert docs",
    notes: "",
    statusGroup: "New",
    status: "Assigned",
    salesPerson: "Kibran",
    zcrm: "79117800001753310010",
    tcvRaw: "",
    closing: "2026-03-31",
  },
  {
    received: "2025-11-10",
    source: "Account Mining",
    account: "Accutrend",
    potential: "SOS Test_UBO Data",
    notes: "Samples shared",
    statusGroup: "In Progress",
    status: "Awaiting Customer Feedback",
    salesPerson: "Kibran",
    zcrm: "",
    tcvRaw: "",
    closing: "2026-03-31",
  },
  {
    received: "2025-11-11",
    source: "Account Mining",
    account: "Accutrend",
    potential: "Canada Additional Province/Territories and TIN",
    notes: "Approach and timeline details shared",
    statusGroup: "Closed",
    status: "Awaiting Customer Response",
    salesPerson: "Kibran",
    zcrm: "",
    tcvRaw: "",
    closing: "2026-03-31",
  },
  {
    received: "2025-11-17",
    source: "Marketing Lead",
    account: "Sthree",
    potential: "Follow up sent",
    notes: "No response",
    statusGroup: "New",
    status: "Attempted Contact",
    salesPerson: "Cathy",
    zcrm: "79117800001762010470",
    tcvRaw: "",
    closing: "2026-03-31",
  },
  {
    received: "2025-11-20",
    source: "Marketing Lead",
    account: "Mindset Medical",
    potential: "To update",
    notes: "Qualified",
    statusGroup: "New",
    status: "Assigned",
    salesPerson: "Kibran",
    zcrm: "79117800001765250000",
    tcvRaw: "",
    closing: "2026-03-31",
  },
  {
    received: "2025-11-22",
    source: "Marketing Lead",
    account: "cchs-satx",
    potential: "Turn text from my images to real text of a document",
    notes: "",
    statusGroup: "New",
    status: "Assigned",
    salesPerson: "Kibran",
    zcrm: "79117800001767580000",
    tcvRaw: "",
    closing: "2026-03-31",
  },
  {
    received: "2025-11-24",
    source: "Account Mining",
    account: "LexisNexis Intelligize",
    potential: "Microfiche Data Capture Services",
    notes: "Proposal submitted",
    statusGroup: "In Progress",
    status: "Proposal Sent",
    salesPerson: "Kibran",
    zcrm: "79117800001769570000",
    tcvRaw: "$40,00,000",
    closing: "2026-03-31",
  },
  {
    received: "2025-11-29",
    source: "Marketing Lead",
    account: "Mrpm",
    potential: "Unstructured Data Extraction",
    notes: "",
    statusGroup: "New",
    status: "Assigned",
    salesPerson: "Kibran",
    zcrm: "79117800001774500020",
    tcvRaw: "",
    closing: "2026-03-31",
  },
  {
    received: "2025-12-09",
    source: "Account Mining",
    account: "LexisNexis Risk",
    potential: "MI One Court of Justice Name Search",
    notes: "Proposal submitted",
    statusGroup: "In Progress",
    status: "Proposal Sent",
    salesPerson: "Kibran",
    zcrm: "79117800001782100000",
    tcvRaw: "$1,43,000",
    closing: "2026-03-31",
  },
  {
    received: "2025-12-15",
    source: "Account Mining",
    account: "LexisNexis Risk",
    potential: "Court & International Source Collections",
    notes: "Demo readiness in progress - Scheduled for Jan 6th.",
    statusGroup: "In Progress",
    status: "Demo Completed",
    salesPerson: "Kibran",
    zcrm: "",
    tcvRaw: "",
    closing: "2026-03-31",
  },
  {
    received: "2025-12-16",
    source: "Account Mining",
    account: "DataAxle",
    potential: "SOS Data (30 States)",
    notes: "Query sent. Kibran to get back",
    statusGroup: "In Progress",
    status: "Awaiting Customer Feedback",
    salesPerson: "Kibran",
    zcrm: "",
    tcvRaw: "",
    closing: "2026-03-31",
  },
  {
    received: "2026-01-07",
    source: "Account Mining",
    account: "D&B India",
    potential: "MCA Newly Registered Companies",
    notes: "",
    statusGroup: "New",
    status: "Assigned",
    salesPerson: "MJ",
    zcrm: "",
    tcvRaw: "",
    closing: "2026-03-31",
  },
  {
    received: "2026-01-10",
    source: "Sales Lead",
    account: "D&B UK",
    potential: "URL Discovery and Financial Data extraction",
    notes:
      "Sent the deck and requested for meeting. SOW changes to be shared with the client.",
    statusGroup: "Closed",
    status: "Awaiting Customer Response",
    salesPerson: "Cathy",
    zcrm: "",
    tcvRaw: "",
    closing: "2026-03-31",
  },
  {
    received: "2026-01-13",
    source: "Marketing Lead",
    account: "360degree",
    potential: "Data Analysis for Due diligence and Acquisitions",
    notes: "",
    statusGroup: "New",
    status: "Assigned",
    salesPerson: "MJ",
    zcrm: "79117800001807430020",
    tcvRaw: "",
    closing: "2026-03-31",
  },
  {
    received: "2026-01-14",
    source: "Marketing Lead",
    account: "bluCognition",
    potential: "SOS Data Aggregation",
    notes: "Proposal submitted",
    statusGroup: "In Progress",
    status: "Proposal Sent",
    salesPerson: "MJ",
    zcrm: "79117800001808490000",
    tcvRaw: "$50,000",
    closing: "2026-03-31",
  },
  {
    received: "2026-01-21",
    source: "Sales Lead",
    account: "DM Clinical Research",
    potential: "Unstructured Data Extraction",
    notes: "Deck shared",
    statusGroup: "Closed",
    status: "Awaiting Customer Response",
    salesPerson: "Kibran",
    zcrm: "",
    tcvRaw: "",
    closing: "2026-03-31",
  },
  {
    received: "2026-01-21",
    source: "Marketing Lead",
    account: "Contingency Capital",
    potential: "Food distributor data",
    notes: "Revised samples shared",
    statusGroup: "In Progress",
    status: "Awaiting Customer Feedback",
    salesPerson: "Kibran",
    zcrm: "79117800001812600000",
    tcvRaw: "",
    closing: "2026-03-31",
  },
  {
    received: "2026-01-21",
    source: "Marketing Lead",
    account: "Contingency Capital",
    potential: "bespoke data",
    notes: "",
    statusGroup: "New",
    status: "Assigned",
    salesPerson: "Kibran",
    zcrm: "79117800001812600000",
    tcvRaw: "",
    closing: "2026-03-31",
  },
  {
    received: "2026-01-21",
    source: "Marketing Lead",
    account: "2MK Architects",
    potential: "Bulk extraction",
    notes: "",
    statusGroup: "New",
    status: "Assigned",
    salesPerson: "Kibran",
    zcrm: "79117800001812660010",
    tcvRaw: "",
    closing: "2026-03-31",
  },
  {
    received: "2026-01-28",
    source: "Marketing Lead",
    account: "Bitroixsolution",
    potential: "need restaurants data",
    notes: "Pakistan lead - need to check whether to take it lead forward",
    statusGroup: "Closed",
    status: "Closed – No Decision",
    salesPerson: "MJ",
    zcrm: "79117800001815400000",
    tcvRaw: "",
    closing: "2026-03-31",
  },
  {
    received: "2026-01-28",
    source: "Marketing Lead",
    account: "Jmijustice",
    potential: "unstructured-data-extraction",
    notes: "",
    statusGroup: "New",
    status: "Assigned",
    salesPerson: "Kibran",
    zcrm: "79117800001815020000",
    tcvRaw: "",
    closing: "2026-03-31",
  },
  {
    received: "2026-01-29",
    source: "Marketing Lead",
    account: "Finexcu",
    potential:
      "Looking to extract data from multiple platforms into one location",
    notes: "Pitch points shared",
    statusGroup: "In Progress",
    status: "Awaiting Customer Feedback",
    salesPerson: "Kibran",
    zcrm: "",
    tcvRaw: "",
    closing: "2026-03-31",
  },
  {
    received: "2026-02-01",
    source: "Marketing Lead",
    account: "Alamo Tile & Stone",
    potential: "Image to Text",
    notes: "",
    statusGroup: "New",
    status: "Assigned",
    salesPerson: "Kibran",
    zcrm: "79117800001748450190",
    tcvRaw: "",
    closing: "2026-03-31",
  },
  {
    received: "2026-02-02",
    source: "Sales Lead",
    account: "S&P Mobility",
    potential: "OEM Data extraction",
    notes:
      "Gaurav attending the conference that we are sponsoring next week- Data Products and Platform",
    statusGroup: "In Progress",
    status: "Awaiting Customer Feedback",
    salesPerson: "Cathy",
    zcrm: "",
    tcvRaw: "",
    closing: "2026-03-31",
  },
  {
    received: "2026-02-06",
    source: "Marketing Lead",
    account: "Rockwatergrp",
    potential: "Real time API business lookups against SOS data",
    notes: "",
    statusGroup: "In Progress",
    status: "Feasibility Check",
    salesPerson: "Kibran",
    zcrm: "",
    tcvRaw: "$50,000",
    closing: "2026-03-31",
  },
  {
    received: "2026-02-10",
    source: "Account Mining",
    account: "LexisNexis Risk",
    potential: "WI - Circuit Courts Case search",
    notes: "Proposal submitted",
    statusGroup: "In Progress",
    status: "Proposal Sent",
    salesPerson: "Kibran",
    zcrm: "79117800001820330000",
    tcvRaw: "$7,140",
    closing: "2026-03-31",
  },
  {
    received: "2026-02-10",
    source: "Marketing Lead",
    account: "Suisat",
    potential: "To update",
    notes: "Qualified",
    statusGroup: "New",
    status: "Assigned",
    salesPerson: "Cathy",
    zcrm: "",
    tcvRaw: "",
    closing: "2026-03-31",
  },
  {
    received: "2026-02-11",
    source: "Account Mining",
    account: "CSG",
    potential: "Recreational Facilities",
    notes: "Samples shared. Awaiting feedback",
    statusGroup: "In Progress",
    status: "Awaiting Customer Feedback",
    salesPerson: "Kibran",
    zcrm: "79117800001815380000",
    tcvRaw: "",
    closing: "2026-03-31",
  },
  {
    received: "2026-02-14",
    source: "Marketing Lead",
    account: "bluCognition",
    potential: "SOS Data Aggregation",
    notes: "Proposal submitted",
    statusGroup: "In Progress",
    status: "Proposal Sent",
    salesPerson: "MJ",
    zcrm: "79117800001808490000",
    tcvRaw: "$50,000",
    closing: "2026-03-31",
  },
  {
    received: "2026-02-17",
    source: "Marketing Lead",
    account: "Housecall Pro",
    potential: "SOS Data Aggregation",
    notes: "",
    statusGroup: "In Progress",
    status: "Feasibility Check",
    salesPerson: "Kibran",
    zcrm: "",
    tcvRaw: "",
    closing: "2026-03-31",
  },
  {
    received: "2026-02-19",
    source: "Marketing Lead",
    account: "Williamsbu",
    potential: "Unstructured Data Extraction",
    notes: "Samples shared. Awaiting response",
    statusGroup: "In Progress",
    status: "Awaiting Customer Feedback",
    salesPerson: "Kibran",
    zcrm: "79117800001825930000",
    tcvRaw: "",
    closing: "2026-03-31",
  },
];

export const mockEntries: SalesEntry[] = rawEntries.map((r, i) => {
  return {
    id: BigInt(i + 1),
    receivedDate: r.received,
    leadSource: r.source,
    accountName: r.account,
    potential: r.potential,
    notes: r.notes,
    statusGroup: r.statusGroup,
    status: r.status,
    salesPerson: r.salesPerson,
    zcrmLink: r.zcrm,
    tcv: parseTCV(r.tcvRaw),
    closingDate: r.closing,
    createdAt: BASE_NS - DAY_NS * BigInt(rawEntries.length - i),
  };
});

export function computeMockDashboardStats(): DashboardStats {
  const today = new Date("2026-03-02");
  const thirtyDaysOut = new Date(today);
  thirtyDaysOut.setDate(thirtyDaysOut.getDate() + 30);

  let totalTCV = 0;
  let newCount = 0n;
  let inProgressCount = 0n;
  let closedCount = 0n;
  let newTCV = 0;
  let inProgressTCV = 0;
  let closedTCV = 0;

  let salesLeadCount = 0n;
  let marketingLeadCount = 0n;
  let accountMiningCount = 0n;
  let referralCount = 0n;
  let salesLeadTCV = 0;
  let marketingLeadTCV = 0;
  let accountMiningTCV = 0;
  let referralTCV = 0;

  for (const e of mockEntries) {
    totalTCV += e.tcv;
    const sg = e.statusGroup;
    if (sg === "New") {
      newCount++;
      newTCV += e.tcv;
    } else if (sg === "In Progress") {
      inProgressCount++;
      inProgressTCV += e.tcv;
    } else {
      closedCount++;
      closedTCV += e.tcv;
    }

    const ls = e.leadSource;
    if (ls === "Sales Lead") {
      salesLeadCount++;
      salesLeadTCV += e.tcv;
    } else if (ls === "Marketing Lead") {
      marketingLeadCount++;
      marketingLeadTCV += e.tcv;
    } else if (ls === "Account Mining") {
      accountMiningCount++;
      accountMiningTCV += e.tcv;
    } else {
      referralCount++;
      referralTCV += e.tcv;
    }
  }

  const recentEntries = [...mockEntries]
    .sort((a, b) => Number(b.createdAt - a.createdAt))
    .slice(0, 5);

  const upcomingClosings = mockEntries.filter((e) => {
    if (!e.closingDate) return false;
    const closeMs = new Date(`${e.closingDate}T00:00:00`).getTime();
    return closeMs >= today.getTime() && closeMs <= thirtyDaysOut.getTime();
  });

  return {
    totalEntries: BigInt(mockEntries.length),
    totalTCV,
    countByStatusGroup: {
      new: newCount,
      inProgress: inProgressCount,
      closed: closedCount,
    },
    tcvByStatusGroup: {
      new: newTCV,
      inProgress: inProgressTCV,
      closed: closedTCV,
    },
    countByLeadSource: {
      salesLead: salesLeadCount,
      marketingLead: marketingLeadCount,
      accountMining: accountMiningCount,
      referral: referralCount,
    },
    tcvByLeadSource: {
      salesLead: salesLeadTCV,
      marketingLead: marketingLeadTCV,
      accountMining: accountMiningTCV,
      referral: referralTCV,
    },
    recentEntries,
    upcomingClosings,
  };
}
