/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const StatusGroupCounts = IDL.Record({
  'new' : IDL.Nat,
  'closed' : IDL.Nat,
  'inProgress' : IDL.Nat,
});
export const LeadSourceTCV = IDL.Record({
  'marketingLead' : IDL.Float64,
  'referral' : IDL.Float64,
  'accountMining' : IDL.Float64,
  'salesLead' : IDL.Float64,
});
export const SalesEntry = IDL.Record({
  'id' : IDL.Nat,
  'tcv' : IDL.Float64,
  'status' : IDL.Text,
  'statusGroup' : IDL.Text,
  'createdAt' : IDL.Int,
  'salesPerson' : IDL.Text,
  'receivedDate' : IDL.Text,
  'accountName' : IDL.Text,
  'notes' : IDL.Text,
  'closingDate' : IDL.Text,
  'leadSource' : IDL.Text,
  'zcrmLink' : IDL.Text,
  'potential' : IDL.Text,
});
export const StatusGroupTCV = IDL.Record({
  'new' : IDL.Float64,
  'closed' : IDL.Float64,
  'inProgress' : IDL.Float64,
});
export const LeadSourceCounts = IDL.Record({
  'marketingLead' : IDL.Nat,
  'referral' : IDL.Nat,
  'accountMining' : IDL.Nat,
  'salesLead' : IDL.Nat,
});
export const DashboardStats = IDL.Record({
  'totalEntries' : IDL.Nat,
  'countByStatusGroup' : StatusGroupCounts,
  'tcvByLeadSource' : LeadSourceTCV,
  'totalTCV' : IDL.Float64,
  'upcomingClosings' : IDL.Vec(SalesEntry),
  'recentEntries' : IDL.Vec(SalesEntry),
  'tcvByStatusGroup' : StatusGroupTCV,
  'countByLeadSource' : LeadSourceCounts,
});

export const idlService = IDL.Service({
  'addEntry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteEntry' : IDL.Func([IDL.Nat], [], []),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getEntries' : IDL.Func([], [IDL.Vec(SalesEntry)], ['query']),
  'getEntriesByLeadSource' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SalesEntry)],
      ['query'],
    ),
  'getEntriesByStatusGroup' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SalesEntry)],
      ['query'],
    ),
  'getEntry' : IDL.Func([IDL.Nat], [SalesEntry], ['query']),
  'updateEntry' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const StatusGroupCounts = IDL.Record({
    'new' : IDL.Nat,
    'closed' : IDL.Nat,
    'inProgress' : IDL.Nat,
  });
  const LeadSourceTCV = IDL.Record({
    'marketingLead' : IDL.Float64,
    'referral' : IDL.Float64,
    'accountMining' : IDL.Float64,
    'salesLead' : IDL.Float64,
  });
  const SalesEntry = IDL.Record({
    'id' : IDL.Nat,
    'tcv' : IDL.Float64,
    'status' : IDL.Text,
    'statusGroup' : IDL.Text,
    'createdAt' : IDL.Int,
    'salesPerson' : IDL.Text,
    'receivedDate' : IDL.Text,
    'accountName' : IDL.Text,
    'notes' : IDL.Text,
    'closingDate' : IDL.Text,
    'leadSource' : IDL.Text,
    'zcrmLink' : IDL.Text,
    'potential' : IDL.Text,
  });
  const StatusGroupTCV = IDL.Record({
    'new' : IDL.Float64,
    'closed' : IDL.Float64,
    'inProgress' : IDL.Float64,
  });
  const LeadSourceCounts = IDL.Record({
    'marketingLead' : IDL.Nat,
    'referral' : IDL.Nat,
    'accountMining' : IDL.Nat,
    'salesLead' : IDL.Nat,
  });
  const DashboardStats = IDL.Record({
    'totalEntries' : IDL.Nat,
    'countByStatusGroup' : StatusGroupCounts,
    'tcvByLeadSource' : LeadSourceTCV,
    'totalTCV' : IDL.Float64,
    'upcomingClosings' : IDL.Vec(SalesEntry),
    'recentEntries' : IDL.Vec(SalesEntry),
    'tcvByStatusGroup' : StatusGroupTCV,
    'countByLeadSource' : LeadSourceCounts,
  });
  
  return IDL.Service({
    'addEntry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteEntry' : IDL.Func([IDL.Nat], [], []),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getEntries' : IDL.Func([], [IDL.Vec(SalesEntry)], ['query']),
    'getEntriesByLeadSource' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SalesEntry)],
        ['query'],
      ),
    'getEntriesByStatusGroup' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SalesEntry)],
        ['query'],
      ),
    'getEntry' : IDL.Func([IDL.Nat], [SalesEntry], ['query']),
    'updateEntry' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };