/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardStats {
  'totalEntries' : bigint,
  'countByStatusGroup' : StatusGroupCounts,
  'tcvByLeadSource' : LeadSourceTCV,
  'totalTCV' : number,
  'upcomingClosings' : Array<SalesEntry>,
  'recentEntries' : Array<SalesEntry>,
  'tcvByStatusGroup' : StatusGroupTCV,
  'countByLeadSource' : LeadSourceCounts,
}
export interface LeadSourceCounts {
  'marketingLead' : bigint,
  'referral' : bigint,
  'accountMining' : bigint,
  'salesLead' : bigint,
}
export interface LeadSourceTCV {
  'marketingLead' : number,
  'referral' : number,
  'accountMining' : number,
  'salesLead' : number,
}
export interface SalesEntry {
  'id' : bigint,
  'tcv' : number,
  'status' : string,
  'statusGroup' : string,
  'createdAt' : bigint,
  'salesPerson' : string,
  'receivedDate' : string,
  'accountName' : string,
  'notes' : string,
  'closingDate' : string,
  'leadSource' : string,
  'zcrmLink' : string,
  'potential' : string,
}
export interface StatusGroupCounts {
  'new' : bigint,
  'closed' : bigint,
  'inProgress' : bigint,
}
export interface StatusGroupTCV {
  'new' : number,
  'closed' : number,
  'inProgress' : number,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'department' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addEntry' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      number,
      string,
    ],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteEntry' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getEntries' : ActorMethod<[], Array<SalesEntry>>,
  'getEntriesByLeadSource' : ActorMethod<[string], Array<SalesEntry>>,
  'getEntriesByStatusGroup' : ActorMethod<[string], Array<SalesEntry>>,
  'getEntry' : ActorMethod<[bigint], SalesEntry>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'updateEntry' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      number,
      string,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];